<Project>
    <PropertyGroup>
        <NativeTestLibrary Condition="'$(NativeTestLibrary)' == '' and '$(OS)' == 'Windows_NT'">$(MSBuildThisFileDirectory)..\native\build-msvc\NukedSC55Sharp.Native.dll</NativeTestLibrary>
    </PropertyGroup>
    <ItemGroup Condition="Exists('$(NativeTestLibrary)')">
        <None Include="$(NativeTestLibrary)"
              Link="$([System.IO.Path]::GetFileName('$(NativeTestLibrary)'))"
              CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
